---
title: "Summary ET Persistence"
author: "Chinmay Deval"
date: "1/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
library(tidyverse)
library(sf)
library(raster)
library(qs)
library(leaflet)
library(mapview)
library(echarts4r)
```


```{r, echo=FALSE}
fields= qs::qread("D:/OneDrive - University of Idaho/MagicValleyData/stats_merged_shp/field_boundaries_with_all_stats.qs")
elv = sf::st_read("D:/OneDrive - University of Idaho/MagicValleyData/Elevation_data/field_stats/elevation_slope_magicValley_field_stats.shp")
```





```{r}
elv = elv %>% as.data.frame()%>% dplyr::select(-geometry)
fields1 = fields %>% dplyr::left_join(elv, by= c("FID"))
```

```{r}
colnames(fields1)
```


```{r}
fields1 %>% dplyr::select(Prsstn_, elvtn_m_d) %>% drop_na() %>% ggplot(aes(elvtn_m_d, Prsstn_))+ geom_point()

```


```{r, echo=FALSE}

fields1 %>% dplyr::select(as.numeric(Prsstn_), as.numeric(elvtn_m_d)) %>% drop_na() %>% cor()
```
```{r}
class(fields1$Prsstn_)

class(fields1$elvtn_m_d)

```


<!-- ### append elevation!!! -->
<!-- range for soil variable -->

```{r, echo=FALSE}
fields_df = fields %>% as.data.frame()%>% dplyr::select(-geometry)
head(fields_df)
```

```{r}
# hist(fields$OverallMax, na.rm= T)

a = fields %>% dplyr::filter(OverallMax > 500)
hist(a$OverallMax, na.rm= T)


```


```{r}
colnames(fields)
```




## Percent persistently different vs twc0150
```{r}
fields_df %>% dplyr::select(Prsstn_, twc0150) %>% drop_na() %>% ggplot(aes(twc0150, Prsstn_))+ geom_point()

```


## Percent persistently different vs twc0150

```{r, echo=FALSE}

fields_df %>% dplyr::select(Prsstn_, twc0150) %>% drop_na() %>% cor()
```


```{r}
fields_df %>% dplyr::select(Prsstn_, dpthtbd) %>% drop_na() %>% ggplot(aes(dpthtbd, Prsstn_))+ geom_point()

```


```{r, echo=FALSE}
fields_df %>% dplyr::select(Prsstn_, OverallMax) %>% drop_na() %>% cor()
```
